config/routes.rb
Rails.application.routes.draw do
    root to: 'home#top'
  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: "companies/sessions",
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <ul class="header-menus">
          <% if user_signed_in? %>
            <li>
              <%= link_to "studentログアウト", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "studentログイン", new_user_session_path %>
            </li>
            <li>
              <%= link_to "student登録", new_user_registration_path %>
            </li>
          <% end %>
               <% if company_signed_in? %>
            <li>
              <%= link_to "companyログアウト", destroy_company_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "companyログイン", new_company_session_path %>
            </li>
            <li>
              <%= link_to "company登録", new_company_registration_path %>
            </li>
          <% end %>
        </ul>
      </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>